import os
import json
import re
import tempfile
import traceback
import urllib.request
import yt_dlp
from mutagen import File as MutagenFile
from mutagen.mp4 import MP4, MP4Cover
from mutagen.easyid3 import EasyID3
from mutagen.id3 import ID3, ID3NoHeaderError

# Configurar directorio temporal seguro por defecto si existe entorno
_APP_TEMP_DIR = os.environ.get("TMPDIR", "")
if _APP_TEMP_DIR and os.path.exists(_APP_TEMP_DIR):
    tempfile.tempdir = _APP_TEMP_DIR

def set_temp_dir(path):
    """Establece la ruta privada de caché de la app para todas las operaciones temporales."""
    global _APP_TEMP_DIR
    if path and os.path.exists(path):
        _APP_TEMP_DIR = path
        os.environ["TMPDIR"] = path
        tempfile.tempdir = path

def clean_title(title):
    """Limpia sufijos típicos de YouTube / YouTube Music en títulos de canciones."""
    if not title:
        return ""
    cleaned = re.sub(
        r'[\(\[\{]\s*(?:official\s*video|official\s*audio|official\s*music\s*video|video\s*oficial|audio\s*oficial|letra|lyrics|video\s*con\s*letra|videoclip|hd|4k|remastered|visualizer|audio|lyric\s*video)\s*[\)\]\}]',
        '',
        title,
        flags=re.IGNORECASE
    )
    return re.sub(r'\s+', ' ', cleaned).strip()

def parse_artist_title(raw_title, uploader=""):
    """Intenta separar 'Artista - Canción' y limpiar el nombre de artista."""
    cleaned = clean_title(raw_title)
    artist = uploader or ""
    title = cleaned

    # Limpiar sufijos típicos del uploader como ' - Topic' o 'VEVO'
    if artist.endswith(" - Topic"):
        artist = artist[:-8].strip()
    elif artist.lower().endswith("vevo"):
        artist = artist[:-4].strip()

    # Si el título contiene ' - ' o ' – '
    if " - " in cleaned:
        parts = cleaned.split(" - ", 1)
        artist = parts[0].strip()
        title = parts[1].strip()
    elif " – " in cleaned:
        parts = cleaned.split(" – ", 1)
        artist = parts[0].strip()
        title = parts[1].strip()

    return artist, title

def _write_cookiefile(cookies_str):
    """Crea un archivo Netscape temporal a partir de un string de cookies."""
    if not cookies_str or not cookies_str.strip():
        return None
    try:
        raw = cookies_str.strip()
        temp = tempfile.NamedTemporaryFile(
            mode='w',
            suffix='.txt',
            delete=False,
            encoding='utf-8',
            dir=_APP_TEMP_DIR if _APP_TEMP_DIR else None
        )
        if "# Netscape HTTP Cookie File" in raw:
            temp.write(raw)
        else:
            temp.write("# Netscape HTTP Cookie File\n")
            temp.write("# https://curl.haxx.se/rfc/cookie_spec.html\n")
            temp.write("# This file was generated by PlayOn\n\n")
            
            # Separar por ';' o por salto de línea
            parts = [p.strip() for p in re.split(r'[;\n]', raw) if p.strip()]
            for item in parts:
                if '=' not in item:
                    continue
                name, val = item.split('=', 1)
                name = name.strip()
                val = val.strip()
                if not name:
                    continue
                # Escribir cookie para dominios clave de YouTube y Google
                for domain in ('.youtube.com', '.google.com', '.googleusercontent.com'):
                    temp.write(f"{domain}\tTRUE\t/\tTRUE\t2147483647\t{name}\t{val}\n")
        temp.close()
        return temp.name
    except Exception as e:
        print(f"Error al generar cookiefile: {e}")
        return None

def _build_ydl_opts(extra_headers=None, cookie_file=None):
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36',
        'Accept-Language': 'es-ES,es;q=0.9,en;q=0.8',
        'Sec-Fetch-Mode': 'navigate',
    }
    if extra_headers:
        headers.update(extra_headers)

    opts = {
        'quiet': True,
        'no_warnings': True,
        'noprogress': True,
        'cachedir': False,
        'nocheckcertificate': True,
        'geo_bypass': True,
        'ignoreerrors': False,
        'socket_timeout': 15,
        'extractor_args': {
            'youtube': {
                'player_client': ['android', 'web'],
            }
        },
        'http_headers': headers,
    }

    if cookie_file and os.path.exists(cookie_file):
        opts['cookiefile'] = cookie_file

    return opts

def get_audio_url(url, cookies_str=""):
    cookie_file = _write_cookiefile(cookies_str)
    ydl_opts = _build_ydl_opts(cookie_file=cookie_file)
    ydl_opts['format'] = 'bestaudio[ext=m4a]/bestaudio[ext=mp4]/bestaudio/best[height<=480]/best'
    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)
            return info.get('url', '')
    except Exception as e:
        return "ERROR:" + str(e) + "\n" + traceback.format_exc()
    finally:
        if cookie_file and os.path.exists(cookie_file):
            try:
                os.remove(cookie_file)
            except Exception:
                pass

def get_playlist_info(url, cookies_str=""):
    """Extrae información completa de una playlist o video individual de YouTube/YT Music."""
    cookie_file = _write_cookiefile(cookies_str)
    ydl_opts = _build_ydl_opts(cookie_file=cookie_file)
    ydl_opts['extract_flat'] = 'in_playlist'
    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)
            if not info:
                return json.dumps({"error": "No se pudo obtener información del enlace"})

            playlist_title = info.get('title', 'Descarga')
            tracks = []

            if 'entries' in info and info['entries']:
                for entry in info['entries']:
                    if not entry:
                        continue
                    vid_id = entry.get('id', '')
                    raw_title = entry.get('title', '')
                    uploader = entry.get('uploader') or entry.get('channel') or ''
                    duration = entry.get('duration') or 0
                    thumbnail = entry.get('thumbnail') or ''

                    artist, title = parse_artist_title(raw_title, uploader)

                    tracks.append({
                        "id": vid_id,
                        "title": title or raw_title,
                        "artist": artist or "Artista desconocido",
                        "duration": int(duration) if duration else 0,
                        "thumbnail": thumbnail,
                        "url": f"https://www.youtube.com/watch?v={vid_id}" if vid_id else url,
                    })
            else:
                # Video individual
                vid_id = info.get('id', '')
                raw_title = info.get('title', '')
                uploader = info.get('uploader') or info.get('channel') or ''
                duration = info.get('duration') or 0
                thumbnail = info.get('thumbnail') or ''

                artist, title = parse_artist_title(raw_title, uploader)

                tracks.append({
                    "id": vid_id,
                    "title": title or raw_title,
                    "artist": artist or "Artista desconocido",
                    "duration": int(duration) if duration else 0,
                    "thumbnail": thumbnail,
                    "url": f"https://www.youtube.com/watch?v={vid_id}" if vid_id else url,
                })

            return json.dumps({
                "title": playlist_title,
                "tracks": tracks,
            })
    except Exception as e:
        return json.dumps({"error": str(e)})
    finally:
        if cookie_file and os.path.exists(cookie_file):
            try:
                os.remove(cookie_file)
            except Exception:
                pass

def download_audio(url, out_path, title="", artist="", album="", thumbnail_url="", cookies_str=""):
    import shutil

    # Usar carpeta temporal interna de la app para descarga 100% libre de restricciones de permisos
    temp_dir = tempfile.mkdtemp(prefix='playon_dl_', dir=_APP_TEMP_DIR if _APP_TEMP_DIR else None)
    temp_base = os.path.join(temp_dir, 'audio')

    cookie_file = _write_cookiefile(cookies_str)
    ydl_opts = _build_ydl_opts(cookie_file=cookie_file)
    ydl_opts.update({
        'format': 'bestaudio[ext=m4a]/bestaudio[ext=mp4]/bestaudio/best[height<=480]/best',
        'outtmpl': temp_base + '.%(ext)s',
        'noplaylist': True,
        'cachedir': False,
        'noprogress': True,
    })

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            if not title and info:
                title = info.get('title', '')
            if not artist and info:
                artist = info.get('uploader', '')
            if not thumbnail_url and info:
                thumbnail_url = info.get('thumbnail', '')

        # Buscar el archivo descargado en el directorio temporal
        downloaded_temp_file = None
        for f in os.listdir(temp_dir):
            full_f = os.path.join(temp_dir, f)
            if os.path.isfile(full_f) and not f.endswith('.txt'):
                downloaded_temp_file = full_f
                break

        if not downloaded_temp_file or not os.path.exists(downloaded_temp_file):
            return "ERROR: no se pudo encontrar el archivo descargado en caché temporal"

        # ── Incrustar etiquetas ID3 / MP4 y carátula (NO BLOQUEANTE) ─────
        try:
            mp4 = MP4(downloaded_temp_file)
            if mp4.tags is None:
                mp4.add_tags()

            parsed_artist, parsed_title = parse_artist_title(title, artist)
            if parsed_title or title:
                mp4.tags['\xa9nam'] = [parsed_title or title]
            if parsed_artist or artist:
                mp4.tags['\xa9ART'] = [parsed_artist or artist]
            if album:
                mp4.tags['\xa9alb'] = [album]

            # Descargar e incrustar carátula si existe thumbnail_url con timeout de 5s
            if thumbnail_url and thumbnail_url.startswith(('http://', 'https://')):
                try:
                    req = urllib.request.Request(
                        thumbnail_url,
                        headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}
                    )
                    with urllib.request.urlopen(req, timeout=5) as resp:
                        img_data = resp.read()
                        if img_data:
                            covr_format = MP4Cover.FORMAT_PNG if thumbnail_url.endswith('.png') else MP4Cover.FORMAT_JPEG
                            mp4.tags['covr'] = [MP4Cover(img_data, imageformat=covr_format)]
                except Exception as cover_err:
                    print(f"PlayOn Info: carátula omitida ({cover_err})")

            mp4.save()
        except Exception as tag_err:
            print(f"PlayOn Info: metadatos MP4 omitidos ({tag_err})")

        # ── Copiar el archivo final a la ruta de destino deseada ─────
        out_dir = os.path.dirname(out_path)
        if out_dir:
            os.makedirs(out_dir, exist_ok=True)

        try:
            shutil.copy2(downloaded_temp_file, out_path)
        except Exception as copy_err:
            print(f"PlayOn Warning: fallo copy2 a {out_path}: {copy_err}, reintentando con buffer 64KB...")
            with open(downloaded_temp_file, 'rb') as src, open(out_path, 'wb') as dst:
                shutil.copyfileobj(src, dst, length=65536)

        return "SUCCESS"
    except Exception as e:
        return "ERROR:" + str(e) + "\n" + traceback.format_exc()
    finally:
        if cookie_file and os.path.exists(cookie_file):
            try:
                os.remove(cookie_file)
            except Exception:
                pass
        try:
            shutil.rmtree(temp_dir, ignore_errors=True)
        except Exception:
            pass

def get_audio_tags(file_path):
    try:
        if not file_path:
            return json.dumps({"error": "Ruta inválida"})

        audio = MutagenFile(file_path)
        if audio is None:
            return json.dumps({"title": "", "artist": "", "album": ""})

        title = ""
        artist = ""
        album = ""

        if isinstance(audio, MP4) or file_path.lower().endswith(('.m4a', '.mp4')):
            tags = audio.tags or {}
            title = str(tags.get('\xa9nam', [''])[0]) if tags.get('\xa9nam') else ""
            artist = str(tags.get('\xa9ART', [''])[0]) if tags.get('\xa9ART') else ""
            album = str(tags.get('\xa9alb', [''])[0]) if tags.get('\xa9alb') else ""
        else:
            if hasattr(audio, 'tags') and audio.tags:
                title = str(audio.tags.get('title', [''])[0]) if audio.tags.get('title') else ""
                artist = str(audio.tags.get('artist', [''])[0]) if audio.tags.get('artist') else ""
                album = str(audio.tags.get('album', [''])[0]) if audio.tags.get('album') else ""

        return json.dumps({"title": title, "artist": artist, "album": album})
    except Exception as e:
        return json.dumps({"error": str(e)})

def set_audio_tags(file_path, title, artist, album):
    try:
        if not file_path:
            return "ERROR: Ruta inválida"

        if file_path.lower().endswith(('.m4a', '.mp4')):
            mp4 = MP4(file_path)
            if mp4.tags is None:
                mp4.add_tags()
            if title: mp4.tags['\xa9nam'] = [title]
            if artist: mp4.tags['\xa9ART'] = [artist]
            if album: mp4.tags['\xa9alb'] = [album]
            mp4.save()
            return "SUCCESS"
        elif file_path.lower().endswith('.mp3'):
            try:
                audio = EasyID3(file_path)
            except ID3NoHeaderError:
                id3 = ID3()
                id3.save(file_path)
                audio = EasyID3(file_path)
            if title: audio['title'] = [title]
            if artist: audio['artist'] = [artist]
            if album: audio['album'] = [album]
            audio.save()
            return "SUCCESS"
        else:
            audio = MutagenFile(file_path, easy=True)
            if audio is not None and hasattr(audio, 'tags') and audio.tags is not None:
                if title: audio['title'] = [title]
                if artist: audio['artist'] = [artist]
                if album: audio['album'] = [album]
                audio.save()
                return "SUCCESS"
            return "ERROR: Formato no soportado para edición de tags"
    except Exception as e:
        return "ERROR: " + str(e) + "\n" + traceback.format_exc()
