org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
kotlin.incremental=false
# Redirige el cache y build a ext4 para evitar problemas con exFAT (no soporta symlinks)
org.gradle.cacheDir=/home/deathtrooper/.gradle/caches
org.gradle.projectCacheDir=/tmp/playon_gradle_cache
org.gradle.buildcacheDir=/tmp/playon_build_cache
